
- name: Upgrade EKS Clusters to Kubernetes Version 1.29
  hosts: localhost
  gather_facts: false
  vars:
    aws_region: "eu-north-1"
    target_version: "1.29"

  tasks:
    - name: Get list of EKS clusters in {{ aws_region }}
      command: >
        aws eks list-clusters --region {{ aws_region }} --output json
      register: cluster_list_raw

    - name: Extract cluster names
      set_fact:
        eks_clusters: "{{ cluster_list_raw.stdout | from_json | dict2items | selectattr('key', 'equalto', 'clusters') | map(attribute='value') | list | first }}"

    - name: Upgrade Kubernetes version for each cluster
      include_tasks: upgrade_one_cluster.yml
      loop: "{{ eks_clusters }}"
      loop_control:
        loop_var: cluster_name

